### ISSUE TITLE
Inverse of ciphertext

### ISSUE THREAD

**Issue by Subanggu** [kimandrik/HEAAN#2]
Hi. 
I tested the function 'testInverseBatch' in TestScheme. 
This function is very awesome and helpful to expand other function that i wanna.
By the way, I have a question about the range of input angle .
This function uses the circularArray for generating random number by using cosine and sine trigonometric function.  whatever angle is inputted, range of cosine and sine function is absolutely  from -1 and 1. 

So, this function can be used only for range of number between -1 and 1? or is there any other way to expand the range?

Thanks:)

**Comment by kimandrik** [comment]
Hello.
We used circularArray just for testing. The most important thing for your input x is that |1 - x| < 1/2, i.e. x should be not far from 1 (That is the reason why we used small angle in the test). The constant 1/2 can be replaced by a larger constant, but in this case, the error will increase. Please, refer to the section 4.2 of https://eprint.iacr.org/2016/421.pdf for more details.
