### ISSUE TITLE
Question about fftInv and fftSpecialInv

### ISSUE THREAD

**Issue by fionser** [kimandrik/HEAAN#5]
Hi,
I have a question about the `fftInv` and `fftSpecialInv`;

* Why `bitReverse` is placed differently in these two methods: `fftInv` call `bitReverse` _after_ the butterfly steps while `fftSpecialInv` call before the butterfly steps;

**Comment by kimandrik** [comment]
Hello,
fftInv is a real fff inverse transformation, and ffiSpecialInv is an embedding transformation (may be we should rename this function to avoid misunderstandings). For embedding transformation the method is a little bit different from fft

**Comment by fionser** [comment]
@kimandrik In my understanding, the specialized operations are used for rotating embedded values;
do the order of `bitReverse` matters in the `fftSpecialnv` ?

**Comment by kimandrik** [comment]
The specialized operations are used to encode/decode the array of values to/from the polynomial. I'm not sure about the possible position of bitReverse. We found a method to evaluate fftSpecialInv, and it works. Maybe you can find another method of evaluating this specialized transformation when bitReverse operation is called after butterfly steps.
