### ISSUE TITLE
install HEAAN library have some trouble

### ISSUE THREAD

**Issue by HsuSage** [kimandrik/HEAAN#6]
After I uncomment /src/HEAAN, I will make all in the /run directory. But I have some error:
Building target: HEAAN
Invoking: GCC C++ Linker
g++ -L/usr/local/lib -o "HEAAN"  ./src/Ciphertext.o ./src/Context.o ./src/EvaluatorUtils.o ./src/HEAAN.o ./src/Key.o ./src/NumUtils.o ./src/Plaintext.o ./src/Ring2Utils.o ./src/Scheme.o ./src/SchemeAlgo.o ./src/SecretKey.o ./src/SerializationUtils.o ./src/StringUtils.o ./src/TestScheme.o ./src/TimeUtils.o   -lntl -lgmp
./src/TestScheme.o：in function ‘NTL::BasicThreadPool* NTL::MakeRaw<NTL::BasicThreadPool, long&>(long&)’中：
TestScheme.cpp:(.text._ZN3NTL7MakeRawINS_15BasicThreadPoolEJRlEEEPT_DpOT0_[_ZN3NTL7MakeRawINS_15BasicThreadPoolEJRlEEEPT_DpOT0_]+0x270)：对‘pthread_create’ Undefined reference
/usr/local/lib/libntl.a(RR.o)：in function ‘NTL::RR* NTL::details_pthread::key_wrapper::set<NTL::RR>(NTL::RR*)’中：
/data/xxx/ntl-11.1.0/src/../include/NTL/tools.h:665：对‘pthread_setspecific’Undefined reference
/usr/local/lib/libntl.a(RR.o)：in function ‘NTL::details_pthread::key_wrapper::key_wrapper(void (*)(void*))’中：
/data/xxx/ntl-11.1.0/src/../include/NTL/tools.h:657：对‘pthread_key_create’Undefined reference
/usr/local/lib/libntl.a(RR.o)：in function ‘NTL::RR* NTL::details_pthread::key_wrapper::set<NTL::RR>(NTL::RR*)’中：
/data/xxx/ntl-11.1.0/src/../include/NTL/tools.h:665：对‘pthread_setspecific’Undefined reference
/usr/local/lib/libntl.a(RR.o)：in function ‘NTL::details_pthread::key_wrapper::key_wrapper(void (*)(void*))’中：
/data/xxx/ntl-11.1.0/src/../include/NTL/tools.h:657：对‘pthread_key_create’Undefined reference
/usr/local/lib/libntl.a(RR.o)：in function ‘NTL::RR* NTL::details_pthread::key_wrapper::set<NTL::RR>(NTL::RR*)’中：
...
collect2: error: ld returned 1 exit status
makefile:45: recipe for target 'HEAAN' failed
make: *** [HEAAN] Error 1

What should I do to solve the error? Please help me, Thank you!

**Comment by kimandrik** [comment]
Hello
Can you please add -pthread in /run/makefile in the line that starts with g++

g++ -pthread -L/usr/local/lib -o "HEAAN" $(OBJS) $(USER_OBJS) $(LIBS)

Hope this should help

**Comment by HsuSage** [comment]
Thank you! It's a good idea.
And I try another way  g++ -L/usr/local/lib -o "HEAAN" $(OBJS) $(USER_OBJS) $(LIBS) -lpthread 
also solve the question.
Regards!
